import { ArrowLeft, CalendarCheck2, CircleHelp, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const terms = [
  ["Reservation requests", "A booking submission is a request, not a guaranteed rental. Velocity Drive will confirm vehicle availability, the final collection point, and any applicable deposit before a rental agreement begins."],
  ["Driver eligibility", "Drivers must present a valid driving licence, satisfy the applicable age and licence-duration requirements, and provide identification and payment details requested at collection."],
  ["Rates, add-ons, and payment", "Displayed daily rates and add-on estimates are planning figures. Confirmed rental charges, taxes, deposits, fuel, tolls, damage charges, and optional coverage are shown before collection in the final rental agreement."],
  ["Collection, return, and changes", "Please collect and return the vehicle at the confirmed time and branch. Notify Velocity Drive promptly if travel plans change; availability, extension charges, and cancellation terms can depend on the requested change."],
  ["Vehicle care and permitted use", "Use the vehicle lawfully, follow road rules, and return it in substantially the same condition, subject to ordinary wear. Do not allow an unapproved driver to operate the vehicle or use it for prohibited commercial, racing, towing, or off-road activity unless expressly agreed."],
  ["Incidents and support", "Report accidents, theft, mechanical concerns, or damage as soon as it is safe to do so. Follow the support instructions provided at collection and preserve any information reasonably needed for an incident report."],
];

export default function BookingTerms() {
  return <div className="min-h-screen bg-[#f7f8f6] text-[#0f1e2e]"><Navbar /><main className="pb-24 pt-14 sm:pt-20"><section className="container"><Link href="/" className="inline-flex items-center gap-2 text-sm font-extrabold text-slate-600 transition hover:text-[#d97706]"><ArrowLeft className="h-4 w-4" /> Back to fleet</Link><div className="mt-10 max-w-3xl"><p className="eyebrow"><span /> Booking information</p><h1 className="mt-5 font-editorial text-5xl leading-[0.92] tracking-[-0.06em] sm:text-7xl">Booking terms and conditions.</h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-600">A clear, practical outline of the conditions that apply when requesting a Velocity Drive rental. Last updated: August 2026.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3"><aside className="rounded-[24px] bg-[#0f1e2e] p-6 text-white lg:col-span-1"><ShieldCheck className="h-6 w-6 text-[#f6b256]" /><h2 className="mt-6 font-editorial text-3xl tracking-[-0.04em]">Read before you reserve.</h2><p className="mt-4 text-sm leading-7 text-slate-300">These project terms are designed to explain the booking flow in plain language. Your confirmed rental agreement controls if it differs from this page.</p></aside><div className="space-y-4 lg:col-span-2">{terms.map(([title, text], index) => <article key={title} className="rounded-[22px] border border-slate-200 bg-white p-6 shadow-[0_12px_34px_rgba(15,30,46,0.05)] sm:p-7"><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#d97706]">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-3 font-editorial text-3xl tracking-[-0.045em]">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></section><section id="privacy" className="container mt-16 scroll-mt-24"><div className="rounded-[26px] border border-slate-200 bg-[#eaf0f3] p-7 sm:p-10"><div className="grid gap-8 lg:grid-cols-2"><div><CalendarCheck2 className="h-6 w-6 text-[#d97706]" /><h2 className="mt-5 font-editorial text-4xl tracking-[-0.05em]">Your reservation details.</h2><p className="mt-4 text-sm leading-7 text-slate-600">The form asks for contact and trip information so a booking request can be prepared. When you sign in, only your Favorites are stored with your account to make them available on your other devices.</p></div><div id="accessibility" className="scroll-mt-24"><CircleHelp className="h-6 w-6 text-[#d97706]" /><h2 className="mt-5 font-editorial text-4xl tracking-[-0.05em]">Questions or accessibility.</h2><p className="mt-4 text-sm leading-7 text-slate-600">For help with a request or an accessibility need, contact the Velocity Drive team before collection. We will aim to provide clear, timely guidance about the available options.</p></div></div></div></section></main><Footer /></div>;
}
