/**
 * Velocity Drive visual system: Modern Motor Journal — a light automotive editorial with an off-center hero stage, route labels, and amber reserved for priority states.
 */
import { motion } from "framer-motion";
import { ArrowDownRight, BadgeCheck, CalendarCheck2, CarFront, CircleDollarSign, Clock3, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import BookingModal from "@/components/BookingModal";
import CarGrid, { type PassengerBand, type PriceBand } from "@/components/CarGrid";
import ContactSection from "@/components/ContactSection";
import Footer from "@/components/Footer";
import HeroSearch, { type QuickSearchCriteria } from "@/components/HeroSearch";
import Navbar from "@/components/Navbar";
import TripDesk from "@/components/TripDesk";
import { fleet, isCarAvailableForDates, type CarType, type FleetCar } from "@/data/fleet";
import { readStoredValue, type TripRecord, writeStoredValue } from "@/lib/velocityStore";
import { useFavorites } from "@/lib/useFavorites";
import { staticAssetPath } from "@/lib/staticDemo";
import { toast } from "sonner";

type SortBy = "featured" | "low" | "high";
const pageReveal = { hidden: { opacity: 0, y: 8 }, visible: { opacity: 1, y: 0 } };

export default function Home() {

  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<"All" | CarType>("All");
  const [sortBy, setSortBy] = useState<SortBy>("featured");
  const [priceBand, setPriceBand] = useState<PriceBand>("all");
  const [passengerBand, setPassengerBand] = useState<PassengerBand>("all");
  const [isFiltering, setIsFiltering] = useState(false);
  const hasInitializedFilters = useRef(false);
  const [selectedCar, setSelectedCar] = useState<FleetCar | null>(null);
  const [rentalCriteria, setRentalCriteria] = useState<QuickSearchCriteria>({ location: "Bishkek Downtown Hub", pickupDate: "", returnDate: "", carType: "All" });
  const { savedCarIds, toggleFavorite, isSynced: areFavoritesSynced } = useFavorites();
  const [bookings, setBookings] = useState<TripRecord[]>(() => readStoredValue("velocity-drive-bookings", []));
  useEffect(() => { writeStoredValue("velocity-drive-bookings", bookings); }, [bookings]);
  useEffect(() => {
    if (!hasInitializedFilters.current) {
      hasInitializedFilters.current = true;
      return;
    }
    setIsFiltering(true);
    const timer = window.setTimeout(() => setIsFiltering(false), 280);
    return () => window.clearTimeout(timer);
  }, [searchTerm, selectedCategory, sortBy, priceBand, passengerBand, rentalCriteria]);
  const filteredFleet = useMemo(() => {
    const normalizedSearch = searchTerm.trim().toLowerCase();
    const visible = fleet.filter((car) => (!normalizedSearch || `${car.name} ${car.modelYear} ${car.type} ${car.fuel}`.toLowerCase().includes(normalizedSearch)) && (selectedCategory === "All" || car.type === selectedCategory) && (priceBand === "all" || priceBand === "under-70" && car.rate < 70 || priceBand === "70-100" && car.rate >= 70 && car.rate <= 100 || priceBand === "over-100" && car.rate > 100) && (passengerBand === "all" || passengerBand === "five" && car.seats <= 5 || passengerBand === "six-plus" && car.seats >= 6) && isCarAvailableForDates(car, rentalCriteria.pickupDate, rentalCriteria.returnDate));
    return [...visible].sort((a, b) => sortBy === "low" ? a.rate - b.rate : sortBy === "high" ? b.rate - a.rate : 0);
  }, [searchTerm, selectedCategory, sortBy, priceBand, passengerBand, rentalCriteria]);
  const handleQuickSearch = (criteria: QuickSearchCriteria) => { setRentalCriteria(criteria); setSelectedCategory(criteria.carType); document.querySelector("#fleet")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const handleToggleSaved = (carId: string) => { const car = fleet.find((entry) => entry.id === carId); const removing = savedCarIds.includes(carId); toggleFavorite(carId); if (car) toast.success(removing ? `${car.name} removed from Favorites.` : `${car.name} added to Favorites.`); };
  const handleBookingComplete = (booking: TripRecord) => setBookings((current) => [booking, ...current.filter((item) => item.id !== booking.id)].slice(0, 6));
  const savedCars = fleet.filter((car) => savedCarIds.includes(car.id));
  const clearFleetFilters = () => { setSearchTerm(""); setSelectedCategory("All"); setSortBy("featured"); setPriceBand("all"); setPassengerBand("all"); };
  const availabilityLabel = rentalCriteria.pickupDate || rentalCriteria.returnDate ? `Showing ${filteredFleet.length} available vehicle${filteredFleet.length === 1 ? "" : "s"} for ${rentalCriteria.pickupDate || "your selected pick-up"} → ${rentalCriteria.returnDate || "your selected return"} from ${rentalCriteria.location}.` : "Showing the complete demo fleet. Select pick-up and return dates to refresh availability.";

  return <div id="home" className="min-h-screen overflow-x-hidden bg-[#f7f8f6] text-[#0f1e2e]"><Navbar /><main>
    <section className="hero-atmosphere relative overflow-hidden bg-[#eaf0f3] pb-4 pt-14 sm:pt-18 lg:pb-8 lg:pt-18 xl:pt-22"><div className="absolute right-0 top-0 hidden h-full w-[42%] bg-white/45 lg:block" /><div className="wide-shell relative z-10"><div className="grid items-center gap-12 lg:grid-cols-[minmax(0,1.1fr)_minmax(500px,0.9fr)] lg:gap-12 xl:gap-16 2xl:grid-cols-[minmax(0,0.78fr)_minmax(720px,1.22fr)] 2xl:gap-10">
      <motion.div initial="hidden" animate="visible" transition={{ duration: 0.35, ease: [0.23, 1, 0.32, 1] }} variants={pageReveal} className="hero-copy pb-4 lg:pb-10 xl:pb-14"><p className="eyebrow"><span /> Modern car rental, considered</p><h1 className="mt-6 max-w-[790px] font-editorial text-[clamp(2.9rem,10vw,4.25rem)] leading-[0.93] tracking-[-0.055em] text-[#0f1e2e] sm:text-[clamp(3.4rem,6vw,4.75rem)] lg:text-[clamp(4.5rem,4.7vw,5.6rem)]"><span className="lg:block lg:whitespace-nowrap">The fleet for a</span> <em className="font-normal text-[#0f1e2e] sm:whitespace-nowrap">well-planned</em> <span className="lg:whitespace-nowrap">way forward.</span></h1><p className="mt-7 max-w-[34rem] text-[15px] leading-7 text-slate-600 sm:text-base lg:mt-8 lg:text-[17px] lg:leading-8">From weekday work to a weekend away, select a vehicle with clear pricing, practical details, and less friction at every turn.</p><div className="mt-8 flex flex-wrap gap-x-8 gap-y-3 text-xs font-extrabold text-slate-600 lg:mt-9 lg:text-sm"><span className="flex items-center gap-2"><BadgeCheck className="h-4 w-4 text-[#0f1e2e]" /> Clear daily rates</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#0f1e2e]" /> Reservation support</span></div></motion.div>
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08, duration: 0.35, ease: [0.23, 1, 0.32, 1] }} className="relative self-stretch lg:min-h-[540px] xl:min-h-[610px] 2xl:min-h-[720px]"><div className="relative h-full min-h-[350px] overflow-hidden rounded-[38px] bg-[#0f1e2e] shadow-[0_28px_70px_rgba(15,30,46,0.14)] sm:rounded-tl-[70px] lg:rounded-tl-[96px] lg:rounded-br-[48px]"><img src={staticAssetPath("/manus-storage/velocity-hero_0ffdea12.jpg")} alt="Executive sedan on a bright coastal boulevard" className="h-full w-full object-cover object-center 2xl:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-[#0f1e2e]/62 via-transparent to-transparent" /><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between gap-4 text-white sm:bottom-7 sm:left-7 sm:right-7"><span className="max-w-[230px] text-sm font-semibold leading-5 text-white/90 lg:text-[15px] lg:leading-6">Effortless to choose. Better to drive.</span><span className="shrink-0 rounded-full border border-white/30 bg-white/10 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[0.16em] backdrop-blur-sm">Fleet note 01</span></div></div><div className="absolute -right-2 top-8 hidden rounded-[18px] bg-[#d97706] p-4 text-white shadow-[0_18px_34px_rgba(180,83,9,0.28)] sm:block lg:-right-5 xl:p-5"><CarFront className="h-5 w-5" /><p className="mt-4 text-[10px] font-extrabold uppercase tracking-[0.14em] text-white/75">Today’s view</p><p className="mt-1 font-editorial text-3xl tracking-[-0.05em] xl:text-4xl">4 cars</p></div></motion.div>
    </div><motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.16, duration: 0.35, ease: [0.23, 1, 0.32, 1] }} className="relative z-20 translate-y-7 lg:translate-y-9"><HeroSearch onSearch={handleQuickSearch} /></motion.div></div></section>
    <FleetBanner cars={fleet} />
    <CarGrid cars={filteredFleet} searchTerm={searchTerm} selectedCategory={selectedCategory} sortBy={sortBy} priceBand={priceBand} passengerBand={passengerBand} savedCarIds={savedCarIds} availabilityLabel={availabilityLabel} isFiltering={isFiltering} onSearchChange={setSearchTerm} onCategoryChange={setSelectedCategory} onSortChange={setSortBy} onPriceBandChange={setPriceBand} onPassengerBandChange={setPassengerBand} onClearFilters={clearFleetFilters} onBook={setSelectedCar} onToggleSaved={handleToggleSaved} />
    <TripDesk savedCars={savedCars} bookings={bookings} onBook={setSelectedCar} onRemoveSaved={handleToggleSaved} onClearBookings={() => setBookings([])} areFavoritesSynced={areFavoritesSynced} />
    <section id="how-it-works" className="scroll-mt-24 border-y border-slate-200 bg-white py-[4.5rem] sm:py-20"><div className="container"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className="eyebrow"><span /> A simpler route</p><h2 className="mt-5 max-w-sm font-editorial text-4xl leading-[0.98] tracking-[-0.055em] text-[#0f1e2e] sm:text-5xl">Three decisions, one smooth departure.</h2></div><p className="max-w-xl justify-self-end text-sm leading-7 text-slate-600">Velocity Drive keeps the rental workflow direct: choose the right vehicle, enter the practical details, and submit a clear reservation request.</p></div><div className="route-rule mt-10" /><div className="mt-8 grid gap-5 md:grid-cols-3"><ProcessStep number="01" icon={<CarFront />} title="Choose your vehicle" text="Compare the fleet through usable specification details and a straightforward daily rate." /><ProcessStep number="02" icon={<CalendarCheck2 />} title="Set the dates" text="Add your collection window, contact details, and the extras that matter to your trip." /><ProcessStep number="03" icon={<ArrowDownRight />} title="Drive away" text="Receive a reservation reference, then coordinate final availability and collection support." /></div></div></section>
    <section id="why-velocity" className="scroll-mt-24 bg-[#f7f8f6] py-[4.5rem] sm:py-20"><div className="container"><div className="grid gap-12 lg:grid-cols-[1fr_1.05fr] lg:items-center"><div className="relative"><div className="rounded-[30px] bg-[#0f1e2e] p-7 text-white sm:p-10"><p className="fleet-kicker text-[#f6b256]">03 / Made for the details</p><h2 className="mt-5 max-w-md font-editorial text-5xl leading-[0.94] tracking-[-0.06em] sm:text-6xl">Less guesswork. More of the road ahead.</h2><p className="mt-7 max-w-md text-sm leading-7 text-slate-300">This interface makes each important detail legible before the booking request: the car, the cost, the dates, and the practical additions.</p><div className="mt-9 border-t border-white/15 pt-5 text-xs font-bold text-white/55">A polished frontend demonstration for a modern rental workflow.</div></div><div className="absolute -bottom-5 -right-3 hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-xl sm:block"><Sparkles className="h-5 w-5 text-[#0f1e2e]" /><p className="mt-3 font-editorial text-2xl text-[#0f1e2e]">A calmer booking flow.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Benefit icon={<CircleDollarSign />} title="Transparent pricing" text="The daily rate and selected add-ons are recalculated in the reservation view." /><Benefit icon={<Clock3 />} title="Support-minded" text="Contact details and dates stay together, ready for an availability follow-up." /><Benefit icon={<ShieldCheck />} title="Clear before commit" text="Validation highlights the missing details before a request can be submitted." /><Benefit icon={<BadgeCheck />} title="Designed to adapt" text="The layout and controls resize cleanly from a small phone to a wide desktop." /></div></div></div></section>
    <ContactSection />
  </main><Footer /><BookingModal car={selectedCar} onClose={() => setSelectedCar(null)} onBookingComplete={handleBookingComplete} /></div>;
}

function ProcessStep({ number, icon, title, text }: { number: string; icon: React.ReactNode; title: string; text: string }) { return <motion.article initial={{ opacity: 0, y: 8 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.3 }} transition={{ duration: 0.26 }} className="relative rounded-[20px] border border-slate-200 bg-[#f7f8f6] p-6 sm:p-7"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#0f1e2e] text-white">{icon}</span><span className="absolute right-6 top-7 text-[11px] font-extrabold tracking-[0.16em] text-slate-400">{number}</span><h3 className="mt-8 font-editorial text-3xl tracking-[-0.05em] text-[#0f1e2e]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></motion.article>; }
function FleetBanner({ cars }: { cars: FleetCar[] }) { return <section className="fleet-banner border-y border-[#23364a] bg-[#0f1e2e] py-7 text-white sm:py-9"><div className="wide-shell"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-slate-300"><span /> Available vehicles</p><h2 className="mt-3 font-editorial text-3xl tracking-[-0.04em] sm:text-4xl">Choose the car that meets the road.</h2></div><button type="button" onClick={() => document.querySelector("#fleet")?.scrollIntoView({ behavior: "smooth", block: "start" })} className="flex w-fit items-center gap-2 text-sm font-extrabold text-[#f6b256] transition hover:text-white">Explore the complete fleet <ArrowDownRight className="h-4 w-4" /></button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cars.map((car) => <button key={car.id} type="button" onClick={() => document.querySelector("#fleet")?.scrollIntoView({ behavior: "smooth", block: "start" })} className="group flex min-w-0 items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-3 text-left transition hover:-translate-y-0.5 hover:border-[#f6b256]/70 hover:bg-white/10"><img src={car.image} alt="" className="h-14 w-20 shrink-0 rounded-xl object-cover transition duration-200 group-hover:scale-[1.03]" /><span className="min-w-0"><span className="block truncate text-sm font-extrabold">{car.name}</span><span className="mt-1 block text-[11px] font-bold uppercase tracking-[0.12em] text-slate-400">{car.type} · ${car.rate}/day</span></span></button>)}</div></div></section>; }
function Benefit({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-[18px] border border-slate-200 bg-white p-5 transition duration-200 hover:-translate-y-1 hover:border-slate-400 hover:shadow-lg"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf0f3] text-[#0f1e2e]">{icon}</span><h3 className="mt-5 text-sm font-extrabold text-[#0f1e2e]">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p></div>; }
