import { differenceInCalendarDays, parseISO } from "date-fns";
import { motion } from "framer-motion";
import { ArrowLeft, CalendarCheck2, CarFront, Check, Gauge, Heart, Luggage, Settings2, Share2, Sparkles, UsersRound } from "lucide-react";
import { useState } from "react";
import { useLocation, useRoute } from "wouter";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { fleet, getCarById, isCarAvailableForDates } from "@/data/fleet";
import { useFavorites } from "@/lib/useFavorites";
import { useVehicleMeta } from "@/lib/useVehicleMeta";
import { toast } from "sonner";

export default function VehicleDetails() {
  const [, params] = useRoute("/fleet/:id");
  const [, setLocation] = useLocation();
  const car = getCarById(params?.id ?? "");
  const { savedCarIds, toggleFavorite } = useFavorites();
  const [selectedImage, setSelectedImage] = useState(0);
  const [pickupDate, setPickupDate] = useState("");
  const [returnDate, setReturnDate] = useState("");
  useVehicleMeta(car);

  if (!car) {
    return <div className="min-h-screen bg-[#f7f8f6]"><Navbar /><main className="container py-[4.5rem] sm:py-20"><p className="eyebrow"><span /> Vehicle journal</p><h1 className="mt-5 font-editorial text-6xl tracking-[-0.06em] text-[#0f1e2e]">This vehicle is no longer in the fleet.</h1><button onClick={() => setLocation("/#fleet")} className="mt-8 flex items-center gap-2 rounded-xl bg-[#0f1e2e] px-5 py-3 text-sm font-extrabold text-white"><ArrowLeft className="h-4 w-4" /> Return to fleet</button></main><Footer /></div>;
  }

  const isFavorite = savedCarIds.includes(car.id);
  const plannedDays = pickupDate && returnDate ? Math.max(0, differenceInCalendarDays(parseISO(returnDate), parseISO(pickupDate))) : 0;
  const hasDateRange = Boolean(pickupDate && returnDate && plannedDays > 0);
  const isAvailable = hasDateRange && isCarAvailableForDates(car, pickupDate, returnDate);
  const estimate = plannedDays ? plannedDays * car.rate + 16 : car.rate + 16;
  const similarCars = fleet.filter((entry) => entry.id !== car.id && entry.type === car.type).slice(0, 3);
  const handleFavorite = () => { toggleFavorite(car.id); toast.success(isFavorite ? `${car.name} removed from Favorites.` : `${car.name} saved to Favorites.`); };
  const handleShare = async () => {
    const shareData = { title: `${car.modelYear} ${car.name} | Velocity Drive`, text: `Take a look at the ${car.modelYear} ${car.name} on Velocity Drive.`, url: window.location.href };
    try { if (navigator.share) { await navigator.share(shareData); return; } if (navigator.clipboard) { await navigator.clipboard.writeText(window.location.href); toast.success("Vehicle link copied to your clipboard."); return; } window.prompt("Copy this vehicle link", window.location.href); } catch (error) { if ((error as DOMException).name !== "AbortError") toast.error("The vehicle link could not be shared right now."); }
  };

  return <div className="min-h-screen overflow-x-hidden bg-[#f7f8f6] text-[#0f1e2e]"><Navbar /><main>
    <section className="bg-[#eaf0f3] py-[4.5rem] sm:py-20"><div className="container"><button onClick={() => setLocation("/#fleet")} className="flex items-center gap-2 text-xs font-extrabold text-slate-600 transition hover:text-[#d97706]"><ArrowLeft className="h-3.5 w-3.5" /> Back to fleet</button><div className="mt-8 grid gap-10 xl:grid-cols-[1.14fr_0.86fr] xl:items-end"><div><p className="eyebrow"><span /> Vehicle journal / {car.type}</p><h1 className="mt-5 font-editorial text-6xl leading-[0.88] tracking-[-0.065em] text-[#0f1e2e] sm:text-7xl lg:text-8xl">{car.name}</h1><p className="mt-5 max-w-xl text-[16px] leading-8 text-slate-600">{car.description}</p></div><div className="border-l-2 border-[#d97706] pl-5"><p className="fleet-kicker text-slate-400">Daily rate</p><p className="mt-1 font-editorial text-6xl tracking-[-0.065em] text-[#0f1e2e]">${car.rate}<span className="ml-2 font-sans text-base font-bold tracking-normal text-slate-500">/ day</span></p><div className="mt-3 flex flex-wrap gap-2 text-xs font-bold text-slate-600"><span className="rounded-full bg-white px-3 py-2">Weekly planning rate: ${car.weeklyRate}</span><span className="rounded-full bg-white px-3 py-2">{car.modelYear} · {car.exterior}</span></div></div></div></div></section>
    <section className="py-[4.5rem] sm:py-20"><div className="container"><div className="grid gap-7 xl:grid-cols-[1.12fr_0.88fr]"><div><motion.div key={selectedImage} initial={{ opacity: 0.2, scale: 0.99 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.28 }} className="relative aspect-[16/10] overflow-hidden rounded-[30px] bg-[#0f1e2e]"><img src={car.gallery[selectedImage]} alt={`${car.name} gallery view ${selectedImage + 1}`} className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#0f1e2e]/65 to-transparent p-6 text-white"><p className="fleet-kicker text-white/65">Gallery frame {String(selectedImage + 1).padStart(2, "0")}</p><p className="mt-1 font-editorial text-3xl">{car.name} in {car.exterior}</p></div></motion.div><div className="mt-4 grid grid-cols-3 gap-3">{car.gallery.map((image, index) => <button key={`${image}-${index}`} onClick={() => setSelectedImage(index)} aria-label={`Show gallery image ${index + 1}`} className={`relative aspect-[16/10] overflow-hidden rounded-xl border-2 transition ${selectedImage === index ? "border-[#d97706] shadow-md" : "border-transparent opacity-70 hover:opacity-100"}`}><img src={image} alt="" className="h-full w-full object-cover" /><span className="absolute inset-0 bg-[#0f1e2e]/10" /></button>)}</div></div>
      <aside className="h-fit rounded-[24px] border border-slate-200 bg-white p-6 shadow-[0_16px_40px_rgba(15,30,46,0.06)] sm:p-8 xl:sticky xl:top-24"><div className="flex items-start justify-between gap-4"><div><p className="fleet-kicker text-slate-400">The essential details</p><h2 className="mt-3 font-editorial text-4xl tracking-[-0.055em] text-[#0f1e2e]">Ready when you are.</h2></div><div className="flex items-center gap-2"><button onClick={handleShare} aria-label={`Share ${car.name}`} className="flex h-11 w-11 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-500 transition hover:border-[#0f1e2e] hover:text-[#0f1e2e]"><Share2 className="h-4 w-4" /></button><button onClick={handleFavorite} aria-pressed={isFavorite} className={`flex h-11 w-11 items-center justify-center rounded-full border transition ${isFavorite ? "border-[#d97706] bg-orange-50 text-[#d97706]" : "border-slate-200 bg-white text-slate-500 hover:border-[#0f1e2e] hover:text-[#0f1e2e]"}`}><Heart className={`h-4 w-4 ${isFavorite ? "fill-current" : ""}`} /></button></div></div><div className="mt-7 grid grid-cols-2 border-y border-slate-200"><DetailSpec icon={<CarFront />} label="Drive" value={car.drive} /><DetailSpec icon={<Settings2 />} label="Transmission" value={car.transmission} /><DetailSpec icon={<Gauge />} label="Engine" value={car.engine} /><DetailSpec icon={<UsersRound />} label="Cabin" value={`${car.seats} seats`} /><DetailSpec icon={<Sparkles />} label="Efficiency" value={car.efficiency} /><DetailSpec icon={<Luggage />} label="Storage" value={car.cargo} /></div>
        <section className="mt-5 rounded-2xl border border-slate-200 bg-[#f7f8f6] p-4"><div className="flex items-center justify-between gap-3"><div><p className="fleet-kicker text-slate-400">Plan this vehicle</p><p className="mt-1 text-sm font-extrabold text-[#0f1e2e]">Live planning estimate</p></div><CalendarCheck2 className="h-5 w-5 text-[#d97706]" /></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-slate-500">Pick-up<input type="date" value={pickupDate} onChange={(event) => setPickupDate(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs font-bold text-[#0f1e2e]" /></label><label className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-slate-500">Return<input type="date" min={pickupDate || undefined} value={returnDate} onChange={(event) => setReturnDate(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs font-bold text-[#0f1e2e]" /></label></div>{hasDateRange ? <div className={`mt-4 rounded-xl p-3 ${isAvailable ? "bg-green-50" : "bg-orange-50"}`}><p className={`text-xs font-extrabold ${isAvailable ? "text-[#15803d]" : "text-[#b45309]"}`}>{isAvailable ? `${car.name} is available for this demo window.` : "This vehicle is unavailable for this demo window."}</p><p className="mt-1 text-xs font-semibold text-slate-600">{plannedDays} day{plannedDays === 1 ? "" : "s"} · ${car.rate}/day + $16 protection estimate · <strong>${estimate}</strong> planning total</p></div> : <p className="mt-3 text-xs leading-5 text-slate-500">Add two dates to see duration, availability, and a transparent planning estimate.</p>}<button disabled={!isAvailable} onClick={() => setLocation(`/book?car=${car.id}`)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#d97706] px-4 py-3 text-xs font-extrabold text-white transition hover:bg-[#b45309] disabled:cursor-not-allowed disabled:opacity-45"><CalendarCheck2 className="h-4 w-4" /> Continue with these dates</button></section>
        <div className="mt-5 rounded-xl bg-[#eaf0f3] p-4"><p className="fleet-kicker text-slate-400">Demo availability windows</p><p className="mt-2 text-xs font-semibold leading-5 text-slate-600">Unavailable: {car.unavailableWindows.map((window) => `${window.start} → ${window.end}`).join(", ")}.</p></div><button onClick={() => setLocation(`/book?car=${car.id}`)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0f1e2e] px-5 py-4 text-sm font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-[#d97706] active:scale-[0.97]"><CalendarCheck2 className="h-4 w-4" /> Open booking workspace</button><div className="mt-3 grid gap-3 sm:grid-cols-2"><button onClick={handleFavorite} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3.5 text-sm font-extrabold text-[#0f1e2e] transition hover:border-[#0f1e2e]"><Heart className={`h-4 w-4 ${isFavorite ? "fill-[#d97706] text-[#d97706]" : ""}`} />{isFavorite ? "Favorited" : "Favorite"}</button><button onClick={handleShare} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3.5 text-sm font-extrabold text-[#0f1e2e] transition hover:border-[#0f1e2e]"><Share2 className="h-4 w-4" /> Share</button></div></aside></div></div></section>
    <section className="border-y border-slate-200 bg-white py-[4.5rem] sm:py-20"><div className="container"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-start"><div><p className="eyebrow"><span /> 01 / Cabin and technology</p><h2 className="mt-5 max-w-sm font-editorial text-5xl leading-[0.94] tracking-[-0.055em] text-[#0f1e2e]">Useful features for the road ahead.</h2></div><div className="grid gap-3 sm:grid-cols-2">{car.features.map((feature, index) => <div key={feature} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-[#f7f8f6] px-4 py-4"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#eaf0f3] text-[#0f1e2e]"><Check className="h-3.5 w-3.5" /></span><span className="text-sm font-bold text-[#0f1e2e]"><span className="mr-2 text-[11px] font-extrabold tracking-[0.1em] text-[#d97706]">0{index + 1}</span>{feature}</span></div>)}</div></div></div></section>
    {similarCars.length > 0 && <section className="py-[4.5rem] sm:py-20"><div className="container"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow"><span /> Continue exploring</p><h2 className="mt-4 font-editorial text-5xl tracking-[-0.055em]">Similar cars, same clear details.</h2></div><button onClick={() => setLocation("/#fleet")} className="text-sm font-extrabold text-[#b45309]">Explore all vehicles</button></div><div className="mt-8 flex snap-x gap-5 overflow-x-auto pb-3">{similarCars.map((entry) => <button key={entry.id} onClick={() => setLocation(`/fleet/${entry.id}`)} className="w-[280px] shrink-0 snap-start overflow-hidden rounded-[22px] border border-slate-200 bg-white text-left transition hover:-translate-y-1 hover:shadow-lg"><img src={entry.image} alt="" className="aspect-video w-full object-cover" /><span className="block p-5"><span className="fleet-kicker text-slate-400">{entry.type}</span><span className="mt-2 block font-editorial text-3xl">{entry.name}</span><span className="mt-2 block text-sm font-bold text-[#d97706]">${entry.rate} / day</span></span></button>)}</div></div></section>}
  </main><Footer /></div>;
}

function DetailSpec({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="border-b border-r border-slate-200 p-4 even:border-r-0 nth-last-[-n+2]:border-b-0"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#eaf0f3] text-[#0f1e2e]">{icon}</span><p className="fleet-kicker mt-3 text-slate-400">{label}</p><p className="mt-1 text-xs font-extrabold leading-5 text-[#0f1e2e]">{value}</p></div>; }
