/**
 * Velocity Drive visual system: Modern Motor Journal — a compact navy endcap with real, discoverable contact and social destinations.
 */
import { ArrowRight, Facebook, Instagram, Linkedin, Mail, MapPin, Phone } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import BrandLockup from "@/components/BrandLockup";

const socialLinks = [{ label: "Instagram", href: "https://www.instagram.com/", icon: <Instagram className="h-4 w-4" /> }, { label: "LinkedIn", href: "https://www.linkedin.com/", icon: <Linkedin className="h-4 w-4" /> }, { label: "Facebook", href: "https://www.facebook.com/", icon: <Facebook className="h-4 w-4" /> }];

export default function Footer() {
  const [email, setEmail] = useState("");
  const handleNewsletter = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { toast.error("Enter a valid email address to subscribe."); return; } toast.success("You’re on the route list. Look out for a note from Velocity Drive."); setEmail(""); };
  return <footer id="site-footer" className="bg-[#0f1e2e] text-white"><div className="container py-16 sm:py-20"><div className="grid gap-12 lg:grid-cols-[1.25fr_0.75fr_0.95fr]"><div><BrandLockup inverse /><p className="mt-6 max-w-sm text-sm leading-7 text-slate-300">A practical, better-paced way to choose a car for the workdays, weekends, and spaces in between.</p><div className="mt-7 flex gap-2">{socialLinks.map((social) => <a key={social.label} href={social.href} target="_blank" rel="noreferrer" className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/15 text-slate-300 transition hover:border-white/40 hover:bg-white hover:text-[#0f1e2e]" aria-label={`Open ${social.label}`}>{social.icon}</a>)}</div></div><div><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#f6b256]">06 / Reach Velocity</p><div className="mt-6 space-y-4 text-sm text-slate-300"><a href="mailto:drive@velocity.example" className="flex items-center gap-3 transition hover:text-white"><Mail className="h-4 w-4 text-slate-400" />drive@velocity.example</a><a href="tel:+15550148200" className="flex items-center gap-3 transition hover:text-white"><Phone className="h-4 w-4 text-slate-400" />+1 (555) 014-8200</a><p className="flex items-start gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" />215 Harbour Way<br />Downtown Hub</p></div></div><div><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#f6b256]">Fleet notes, occasionally</p><p className="mt-5 text-sm leading-7 text-slate-300">A concise note when a fresh vehicle or useful route idea is worth sharing.</p><form onSubmit={handleNewsletter} className="mt-5 flex rounded-xl border border-white/15 bg-white/5 p-1.5 focus-within:border-[#f6b256]"><input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email" className="min-w-0 flex-1 bg-transparent px-3 text-sm text-white outline-none placeholder:text-slate-500" aria-label="Email for newsletter" /><button aria-label="Subscribe" className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#d97706] text-white transition hover:bg-[#f6b256] hover:text-[#0f1e2e]"><ArrowRight className="h-4 w-4" /></button></form></div></div><div className="mt-14 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs font-semibold text-slate-400 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Velocity Drive. All rights reserved.</p><div className="flex gap-5"><a href="#home" className="hover:text-white">Terms</a><a href="#home" className="hover:text-white">Privacy</a><a href="#home" className="hover:text-white">Accessibility</a></div></div></div></footer>;
}
