/**
 * Velocity Drive visual system: Modern Motor Journal — visible rental controls with explicit native select inputs and dependable date-picker triggers.
 */
import { ArrowRight, CalendarDays, CarFront, ChevronDown, MapPin } from "lucide-react";
import { FormEvent, useRef, useState } from "react";
import { branchLocations, type CarType } from "@/data/fleet";

export type QuickSearchCriteria = { location: string; pickupDate: string; returnDate: string; carType: "All" | CarType; };
type HeroSearchProps = { onSearch: (criteria: QuickSearchCriteria) => void; };
type PickerInput = HTMLInputElement & { showPicker?: () => void };
const labelClass = "whitespace-nowrap text-[10px] font-extrabold uppercase tracking-[0.16em] text-slate-400";
function formatDate(value: string) { if (!value) return "Select date"; const parsed = new Date(`${value}T12:00:00`); return Number.isNaN(parsed.getTime()) ? "Select date" : new Intl.DateTimeFormat("en", { day: "2-digit", month: "short", year: "numeric" }).format(parsed); }

export default function HeroSearch({ onSearch }: HeroSearchProps) {
  const [criteria, setCriteria] = useState<QuickSearchCriteria>({ location: branchLocations[0], pickupDate: "", returnDate: "", carType: "All" });
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSearch(criteria); };
  const setPickupDate = (pickupDate: string) => setCriteria((current) => ({ ...current, pickupDate, returnDate: current.returnDate && current.returnDate < pickupDate ? "" : current.returnDate }));
  return <form onSubmit={handleSubmit} className="rounded-[24px] border border-slate-200 bg-white p-2.5 shadow-[0_20px_60px_rgba(15,30,46,0.12)] sm:p-3"><div className="grid gap-2 lg:grid-cols-[1.2fr_1.03fr_1.03fr_1.03fr_202px] lg:gap-0 lg:overflow-hidden lg:rounded-[17px] lg:bg-slate-50 lg:divide-x lg:divide-slate-200"><SelectField icon={<MapPin className="h-5 w-5" />} label="Pick-up point" value={criteria.location} onChange={(value) => setCriteria({ ...criteria, location: value })} options={branchLocations} /><DateField label="Pick-up date" value={criteria.pickupDate} onChange={setPickupDate} /><DateField label="Return date" value={criteria.returnDate} min={criteria.pickupDate} onChange={(returnDate) => setCriteria({ ...criteria, returnDate })} /><SelectField icon={<CarFront className="h-5 w-5" />} label="Vehicle class" value={criteria.carType} onChange={(value) => setCriteria({ ...criteria, carType: value as QuickSearchCriteria["carType"] })} options={["All vehicles", "SUV", "Sedan", "Electric", "Luxury"]} values={["All", "SUV", "Sedan", "Electric", "Luxury"]} /><button className="flex min-h-[76px] items-center justify-center gap-2 rounded-[16px] bg-[#0f1e2e] px-6 text-[15px] font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-[#24374c] active:scale-[0.97] lg:m-1 lg:min-h-0" type="submit">Find vehicles <ArrowRight className="h-4 w-4" /></button></div><p className="px-2 pt-2 text-[10px] font-bold tracking-[0.02em] text-slate-400 sm:px-3">Choose a date field to open your device calendar. Demo availability refreshes after you select dates and press Find vehicles.</p></form>;
}

function SelectField({ icon, label, value, onChange, options, values }: { icon: React.ReactNode; label: string; value: string; onChange: (value: string) => void; options: string[]; values?: string[] }) { return <div className="group relative flex min-h-[82px] items-center gap-3 rounded-[16px] border border-slate-200 bg-white px-4 transition hover:bg-slate-50 focus-within:border-[#0f1e2e] focus-within:ring-4 focus-within:ring-slate-100 lg:rounded-none lg:border-0 lg:bg-transparent lg:px-5 lg:focus-within:ring-0"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#eaf0f3] text-[#0f1e2e] lg:h-auto lg:w-auto lg:bg-transparent">{icon}</span><span className="min-w-0 flex-1"><span className={labelClass}>{label}</span><select aria-label={label} className="mt-1 block w-full appearance-none bg-transparent pr-2 text-[15px] font-extrabold text-[#0f1e2e] outline-none" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option, index) => <option key={option} value={values?.[index] ?? option}>{option}</option>)}</select></span><ChevronDown className="pointer-events-none h-4 w-4 shrink-0 text-slate-400 transition group-focus-within:text-[#0f1e2e]" /></div>; }

function DateField({ label, value, min, onChange }: { label: string; value: string; min?: string; onChange: (value: string) => void }) {
  const dateRef = useRef<HTMLInputElement>(null);
  const openPicker = () => { const input = dateRef.current as PickerInput | null; if (!input) return; input.focus(); if (typeof input.showPicker === "function") input.showPicker(); else input.click(); };
  return <div className="group relative flex min-h-[82px] items-center gap-3 rounded-[16px] border border-slate-200 bg-white px-4 transition hover:bg-slate-50 focus-within:border-[#0f1e2e] focus-within:ring-4 focus-within:ring-slate-100 lg:rounded-none lg:border-0 lg:bg-transparent lg:px-5 lg:focus-within:ring-0"><button type="button" onClick={openPicker} className="flex min-w-0 flex-1 items-center gap-3 text-left outline-none"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#eaf0f3] text-[#0f1e2e] lg:h-auto lg:w-auto lg:bg-transparent"><CalendarDays className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className={labelClass}>{label}</span><span className="mt-1 block truncate text-[15px] font-extrabold text-[#0f1e2e]">{formatDate(value)}</span><span className="mt-0.5 block text-[10px] font-bold tracking-[0.08em] text-slate-400">dd/mm/yyyy</span></span></button><button type="button" onClick={openPicker} aria-label={`Open ${label} calendar`} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 transition hover:border-[#0f1e2e] hover:text-[#0f1e2e] lg:border-0 lg:bg-transparent"><CalendarDays className="h-4 w-4" /></button><input ref={dateRef} aria-label={label} className="sr-only" type="date" min={min} value={value} onChange={(event) => onChange(event.target.value)} /></div>;
}
