/**
 * Velocity Drive visual system: Modern Motor Journal — understated navy navigation with a direct route to a client-side drive desk.
 */
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Bookmark, Menu, X } from "lucide-react";
import { useState } from "react";
import BrandLockup from "@/components/BrandLockup";

const navItems = [{ label: "Home", href: "#home" }, { label: "Fleet", href: "#fleet" }, { label: "My drive", href: "#my-drive" }, { label: "How it works", href: "#how-it-works" }, { label: "Why Velocity", href: "#why-velocity" }, { label: "Contact", href: "#contact" }];
function scrollToSection(href: string) { document.querySelector(href)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
export default function Navbar() { const [isOpen, setIsOpen] = useState(false); const handleNavigation = (href: string) => { setIsOpen(false); scrollToSection(href); }; return <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-[#f7f8f6]/95 backdrop-blur-xl"><div className="container flex h-[76px] items-center justify-between gap-5"><button className="group text-left" onClick={() => handleNavigation("#home")} aria-label="Return to Velocity Drive home"><span className="transition-transform duration-200 group-hover:-translate-y-0.5"><BrandLockup /></span></button><nav className="hidden items-center gap-6 lg:flex" aria-label="Primary navigation">{navItems.map((item) => <button key={item.href} onClick={() => handleNavigation(item.href)} className="nav-link">{item.label}</button>)}</nav><div className="flex items-center gap-2"><button onClick={() => handleNavigation("#my-drive")} className="hidden h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-extrabold text-[#0f1e2e] transition hover:border-[#0f1e2e] xl:flex"><Bookmark className="h-3.5 w-3.5" /> My drive</button><button onClick={() => handleNavigation("#fleet")} className="hidden items-center gap-2 rounded-xl bg-[#d97706] px-4 py-3 text-sm font-extrabold text-white shadow-[0_8px_20px_rgba(217,119,6,0.18)] transition duration-200 hover:-translate-y-0.5 hover:bg-[#b45309] active:scale-[0.97] sm:flex">Book a vehicle <ArrowUpRight className="h-4 w-4" /></button><button className="flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 bg-white text-[#0f1e2e] transition hover:border-[#0f1e2e] lg:hidden" onClick={() => setIsOpen((current) => !current)} aria-label={isOpen ? "Close menu" : "Open menu"} aria-expanded={isOpen}>{isOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div></div><AnimatePresence>{isOpen && <motion.nav initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2, ease: [0.23, 1, 0.32, 1] }} className="border-t border-slate-200 bg-[#f7f8f6] px-4 py-5 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto flex max-w-xl flex-col gap-1">{navItems.map((item) => <button key={item.href} onClick={() => handleNavigation(item.href)} className="flex w-full items-center justify-between rounded-xl px-4 py-3 text-left text-sm font-bold text-slate-700 transition hover:bg-white hover:text-[#0f1e2e]">{item.label}<ArrowUpRight className="h-4 w-4 text-[#0f1e2e]" /></button>)}<button onClick={() => handleNavigation("#fleet")} className="mt-3 flex items-center justify-center gap-2 rounded-xl bg-[#d97706] px-4 py-3.5 text-sm font-extrabold text-white">Book a vehicle <ArrowUpRight className="h-4 w-4" /></button></div></motion.nav>}</AnimatePresence></header>; }
