/**
 * Velocity Drive visual system: a calm customer-side garage for persistent saved vehicles and reservation references.
 */
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Bookmark, CalendarDays, Heart, MapPin, Scale, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import type { FleetCar } from "@/data/fleet";
import type { TripRecord } from "@/lib/velocityStore";

type TripDeskProps = { savedCars: FleetCar[]; bookings: TripRecord[]; onBook: (car: FleetCar) => void; onRemoveSaved: (carId: string) => void; onClearBookings: () => void; areFavoritesSynced?: boolean; };

export default function TripDesk({ savedCars, bookings, onBook, onRemoveSaved, onClearBookings, areFavoritesSynced = false }: TripDeskProps) {
  const [tab, setTab] = useState<"saved" | "bookings">("saved");
  const activeCount = useMemo(() => tab === "saved" ? savedCars.length : bookings.length, [tab, savedCars.length, bookings.length]);
  return <section id="my-drive" className="scroll-mt-24 border-y border-slate-200 bg-white py-[4.5rem] sm:py-20"><div className="container"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><p className="eyebrow"><span /> 02 / Your drive desk</p><h2 className="mt-5 max-w-sm font-editorial text-4xl leading-[0.98] tracking-[-0.055em] text-[#0f1e2e] sm:text-5xl">Your Favorites and reservation notes, in one place.</h2></div><p className="max-w-2xl justify-self-end text-sm leading-7 text-slate-600">{areFavoritesSynced ? "Your Favorites are securely connected to your account, so they are ready on your other devices." : "Sign in to keep Favorites with your account and make them available on your other devices."}</p></div><div className="route-rule mt-10" /><div className="mt-7 flex flex-wrap items-center justify-between gap-4"><div className="inline-flex rounded-xl border border-slate-200 bg-slate-50 p-1"><button onClick={() => setTab("saved")} className={`flex items-center gap-2 rounded-lg px-3.5 py-2.5 text-xs font-extrabold transition ${tab === "saved" ? "bg-[#0f1e2e] text-white shadow-sm" : "text-slate-500 hover:text-[#0f1e2e]"}`}><Heart className="h-3.5 w-3.5" /> Favorites <span className={`rounded-full px-1.5 py-0.5 text-[9px] ${tab === "saved" ? "bg-white/15 text-white" : "bg-slate-200 text-slate-600"}`}>{savedCars.length}</span></button><button onClick={() => setTab("bookings")} className={`flex items-center gap-2 rounded-lg px-3.5 py-2.5 text-xs font-extrabold transition ${tab === "bookings" ? "bg-[#0f1e2e] text-white shadow-sm" : "text-slate-500 hover:text-[#0f1e2e]"}`}><Bookmark className="h-3.5 w-3.5" /> Reservations <span className={`rounded-full px-1.5 py-0.5 text-[9px] ${tab === "bookings" ? "bg-white/15 text-white" : "bg-slate-200 text-slate-600"}`}>{bookings.length}</span></button></div><div className="flex flex-wrap items-center gap-3"><span className="fleet-kicker text-slate-400">{activeCount ? `${activeCount} item${activeCount === 1 ? "" : "s"} ${areFavoritesSynced && tab === "saved" ? "synced" : "ready"}` : "Ready when you are"}</span>{savedCars.length >= 2 && <Link href="/compare" className="fleet-kicker rounded-lg border border-slate-200 bg-white px-3 py-2 text-[#0f1e2e] transition hover:border-[#d97706] hover:text-[#d97706]"><Scale className="h-3.5 w-3.5" /> Compare 2–3 Favorites</Link>}</div></div><AnimatePresence mode="wait">{tab === "saved" ? <SavedVehicles key="saved" cars={savedCars} onBook={onBook} onRemove={onRemoveSaved} /> : <BookingHistory key="bookings" bookings={bookings} onClear={onClearBookings} />}</AnimatePresence></div></section>;
}

function SavedVehicles({ cars, onBook, onRemove }: { cars: FleetCar[]; onBook: (car: FleetCar) => void; onRemove: (carId: string) => void }) { if (!cars.length) return <EmptyDesk icon={<Heart className="h-5 w-5" />} title="Favorite the vehicles worth returning to." text="Use the heart on any fleet entry or vehicle profile to keep it here for a faster comparison or reservation." />; return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cars.map((car) => <article key={car.id} className="group overflow-hidden rounded-[18px] border border-slate-200 bg-[#f7f8f6] transition hover:-translate-y-1 hover:border-slate-400 hover:shadow-lg"><div className="relative aspect-[16/8] overflow-hidden"><img src={car.image} alt={`${car.name} ${car.modelYear}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]" /><button onClick={() => onRemove(car.id)} aria-label={`Remove ${car.name} from Favorites`} className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-white/95 text-[#d97706] shadow-sm transition hover:bg-[#0f1e2e] hover:text-white"><X className="h-4 w-4" /></button></div><div className="p-4"><div className="flex items-end justify-between gap-4"><div><p className="fleet-kicker text-slate-400">{car.type}</p><h3 className="mt-1 font-editorial text-3xl tracking-[-0.055em] text-[#0f1e2e]">{car.name}</h3></div><p className="font-editorial text-3xl tracking-[-0.055em] text-[#0f1e2e]">${car.rate}<span className="font-sans text-[10px] font-bold tracking-normal text-slate-400">/d</span></p></div><button onClick={() => onBook(car)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0f1e2e] px-4 py-3 text-xs font-extrabold text-white transition hover:bg-[#d97706]">Reserve this vehicle <ArrowUpRight className="h-3.5 w-3.5" /></button></div></article>)}</motion.div>; }
function BookingHistory({ bookings, onClear }: { bookings: TripRecord[]; onClear: () => void }) { if (!bookings.length) return <EmptyDesk icon={<CalendarDays className="h-5 w-5" />} title="No reservation notes yet." text="Once a reservation request is submitted, its reference and trip dates will appear here for quick review." />; return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="mt-6"><div className="overflow-hidden rounded-[18px] border border-slate-200"><div className="hidden grid-cols-[1.3fr_1fr_1fr_0.7fr_auto] gap-4 border-b border-slate-200 bg-[#f7f8f6] px-5 py-3 md:grid"><span className="fleet-kicker text-slate-400">Vehicle</span><span className="fleet-kicker text-slate-400">Pick-up</span><span className="fleet-kicker text-slate-400">Return</span><span className="fleet-kicker text-slate-400">Estimate</span><span className="fleet-kicker text-slate-400">State</span></div>{bookings.map((booking) => <div key={booking.id} className="grid gap-4 border-b border-slate-100 px-4 py-4 last:border-b-0 md:grid-cols-[1.3fr_1fr_1fr_0.7fr_auto] md:items-center md:px-5"><div className="flex items-center gap-3"><img src={booking.carImage} alt="" className="h-10 w-14 rounded-lg object-cover" /><span><span className="block text-sm font-extrabold text-[#0f1e2e]">{booking.carName}</span><span className="mt-0.5 block text-[10px] font-bold text-slate-400">{booking.id}</span></span></div><span className="flex items-center gap-2 text-xs font-bold text-slate-600"><MapPin className="h-3.5 w-3.5 text-slate-400" />{booking.pickupDate}</span><span className="flex items-center gap-2 text-xs font-bold text-slate-600"><CalendarDays className="h-3.5 w-3.5 text-slate-400" />{booking.returnDate}</span><span className="font-editorial text-2xl tracking-[-0.04em] text-[#0f1e2e]">${booking.total}</span><span className="w-fit rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[0.1em] text-[#b45309]">{booking.status}</span></div>)}</div><div className="mt-4 flex justify-end"><button onClick={onClear} className="text-xs font-extrabold text-slate-400 transition hover:text-[#0f1e2e]">Clear local reservation notes</button></div></motion.div>; }
function EmptyDesk({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="mt-6 flex min-h-48 flex-col items-center justify-center rounded-[18px] border border-dashed border-slate-300 bg-[#f7f8f6] px-6 text-center"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf0f3] text-[#0f1e2e]">{icon}</span><h3 className="mt-4 font-editorial text-3xl tracking-[-0.05em] text-[#0f1e2e]">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p></motion.div>; }
